### ISSUE TITLE
Öffnungszeiten bei Terminauswahl

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#21]
mit ist aufgefallen, dass bei der Terminauswahl die **allgemeinen Öffnungszeiten** sinnvoll wären. Rechts neben dem Formular wäre  noch genug Platz. Habt ihr andere Vorschläge?

**Comment by Momo1970** [comment]
ja das wäre ideal

**Comment by daHirsch** [comment]
habe die Öffnungszeiten als rechte Spalte hinzugefügt
