### ISSUE TITLE
Breite von Öffnungszeiten im Smartphone-Modus nicht komplett ausgenutzt

### ISSUE THREAD

**Issue by pghgh** [daHirsch/bloodshare#24]
Die Klasse "col-xs" muss hinzugefügt werden

**Comment by daHirsch** [comment]
danke, mache ich gleich

**Comment by daHirsch** [comment]
behoben, bitte checken und Issue schließen :)

**Comment by pghgh** [comment]
Ich habe es überprüft, danke!
