### ISSUE TITLE
Spenden Intervall Plan Vorschlag

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#26]
Vorschlag: Anstatt nur einen nächsten Termin anzubieten, alle Termine bis zum Jahresende anbieten(im 8 Wochen Takt).
Somit wird die empfohlene Pause des Spenders aus gesundheitlichen Gründen eingehalten und der Spender kann so hilfreich wie möglich sein.

Als Ansporn kann auch die gesamte jährliche Auszahlungssumme, wenn alle Termine (bzw. ähnliche Termine) eingehalten werden, erwähnt werden. Entweder als Text oder zb als "Progressbar" mit Meilensteinen.

**Comment by pghgh** [comment]
Es ist eine gute Idee! Ich werde daran arbeiten.

**Comment by Momo1970** [comment]
Ja finde ich sehr gut

**Comment by pghgh** [comment]
Die aktualisierte Version ist fertig.
