### ISSUE TITLE
Tutorial View Vorschlag(Corporate Design)

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#32]
Danke für die Umsetzung vom Tutorial View!
Da das Dunkelblau(class "bg-primary") nicht zu unserem Corporate Design passt würde ich vorschlagen passendere Farben zu wählen.
Bootstrap kommt uns mit den Klassen "bg-danger" und "bg-dark" entgegen, welche sich bereits durch die gesamte Plattform ziehen.

<img width="1080" alt="vorschlag tutorial" src="https://user-images.githubusercontent.com/10229640/103652702-c3c8b780-4f63-11eb-8507-12b0ace50d0a.PNG">

**Comment by Momo1970** [comment]
So wie du vorgeschlagen hast sieht es wirklich schöner aus

**Comment by daHirsch** [comment]
weiterer Vorschlag:

![image](https://user-images.githubusercontent.com/10229640/103883082-03ff7580-50dd-11eb-895b-f2d1b34af768.png)

**Comment by ChillyVanilly77** [comment]
Mach ich

**Comment by ChillyVanilly77** [comment]
Done: https://github.com/daHirsch/bloodshare/pull/47
