### ISSUE TITLE
Verlinkungen auf Unterseiten überprüfen

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#33]
Bitte überprüft nochmal die Verlinkungen auf den von euch erstellten Unterseiten.

Aufgefallen sind mit Fehler bei FAQ und Terminauswahl und Persönliche Daten.
Bitte schaut trotzdem bei euren Seiten nochmal drüber.
Richtig sind:

 <div class="nav">
              <div class="sb-sidenav-menu-heading">Home</div>
							<a class="nav-link" href="index.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-heart"></i></div>
                                Willkommen
                            </a>
                            <a class="nav-link" href="termin.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-clock"></i></div>
                                Terminauswahl
                            </a>
                            <div class="sb-sidenav-menu-heading">Benutzerkonto</div>
                            
                           <a class="nav-link" href="konto.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                                Persönliche Daten
                            </a>
                           
                            
                            <div class="sb-sidenav-menu-heading">Spenden</div>
                            <a class="nav-link" href="historie.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-history"></i></div>
                                Historie
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                                Spenden Intervall Plan
                            </a>
							
							<div class="sb-sidenav-menu-heading">Hilfe</div>
                            <a class="nav-link" href="tutorial.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-info"></i></div>
                                Tutorial
                            </a>
                            <a class="nav-link" href="faq.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-question"></i></div>
                                FAQ
                            </a>
             </div>
     </div>

**Comment by pghgh** [comment]
"tables.html" und "historie.html" wurden auch überprüft

**Comment by Momo1970** [comment]
ich habe den Fehler in FAQ behoben
