### ISSUE TITLE
Tutorial-View  "Sie" statt "Du"

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#37]
Bitte beim Tutorial, wie bei allen anderen Views, die Spender/innen auch mit Sie ansprechen.

**Comment by Momo1970** [comment]
ja das wäre höfflicher

**Comment by ChillyVanilly77** [comment]
Es geht darum, dem User diese Art von "relaxed vibes" zu geben, sowie auch z.B. Bolt-E-Mails das machen etc.
Welches ja an sich nichts mit "unprofessionell" zu tun hat.
Denn die meinsten die das tun wuerden sind ja eher juengere Leute.

**Comment by daHirsch** [comment]
Wichtig ist dass es auf der gesamten Plattform eindeutig ist. Soll das Tutorial oder der Rest angepasst werden?
Bitte abstimmen

**Comment by ChillyVanilly77** [comment]
Habe vergessen im comment hinzuzufuegen "Ich aendere es dann halt auf 'Sie' " - wesshalb ich das issue ja auch geschlossen habe :v:

**Comment by RegisStudios** [comment]
Wenn Benutzer derzeit überall mit "Sie" angesprochen werden, ist es sinnvoll dies auch beim Tutorial zu tun.
