### ISSUE TITLE
FAQ Schriftfarbe(Corporate Design)

### ISSUE THREAD

**Issue by daHirsch** [daHirsch/bloodshare#38]
Auch bitte die Schriftfarbe beim FAQ View anpassen um Corporate Design zu gewährleisten
Vorschlag: Schriftfarbe dunkel, Pfeile in rot

![image](https://user-images.githubusercontent.com/10229640/103877499-78361b00-50d5-11eb-9033-109e9808b696.png)

**Comment by Momo1970** [comment]
Ja da hast du Recht

**Comment by daHirsch** [comment]
habs angepasst
