### ISSUE TITLE
Redundante/Mehrfache Inklusion von Boostrap-Bundles

### ISSUE THREAD

**Issue by ChillyVanilly77** [daHirsch/bloodshare#43]
Im [tables.html file](https://github.com/daHirsch/bloodshare/blob/main/dist/tables.html) wird Boostrap mehrfach inkludiert und noch dazu verschiedene Versionen.

Betroffene Lines (laut aktuellem `main`-Branch):
- https://github.com/daHirsch/bloodshare/blob/a017b26e9fe74806151683b75dbdc0a52856e5f3/dist/tables.html#L192
- womoeglich diese auch (muesste man im Browser testen/sehen): https://github.com/daHirsch/bloodshare/blob/a017b26e9fe74806151683b75dbdc0a52856e5f3/dist/tables.html#L11

Denn durch die [Line #10](https://github.com/daHirsch/bloodshare/blob/a017b26e9fe74806151683b75dbdc0a52856e5f3/dist/tables.html#L10)
```html
<link href="css/styles.css" rel="stylesheet" />
```
wird Boostrap-Bundle v4.5.3 bereits inkludiert mit echtem Pfad von => `dist/css/styles.css`.

Falls dies anderswo auch passiert, wuerde ich empfehlend dies zu beheben. :v:

**Comment by daHirsch** [comment]
danke für die Info. habs bei meinen Views optimiert. auch die scripts bis auf
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
  <script src="js/scripts.js"></script>

sind überflüssig

**Comment by daHirsch** [comment]
Weiters unnötig sind:

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/datatables-demo.js"></script>

Die brauchen wir noch: (fürs ausklappen der Sidebar und die Klickfunktion rechts oben in der Navbar)
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  <script src="js/scripts.js"></script>

**Comment by pghgh** [comment]
Das Problem wurde gelöst, danke!
